### PR TITLE
Add Some Integration Bees to lookup

### PR DESCRIPTION
**Pull request by Incompleteusern**

### CODE REVIEW

**Comment by vEnhance** [comment]
I think I might prefer something like
```python
lookup["Feb HMMT IntBee"] = "FEBIB"
lookup["Nov HMMT IntBee"] = "NOVIB"
lookup["CHMMC IntBee"] = "CHMMCIB"
lookup["IntBee Quals"] = "MIBQT"
lookup["IntBee"] = "MITIB"
```

what do you think?

**Comment by Incompleteusern** [comment]
That's probably fine, apparently MIT was responsible for the first IntB :eyes:.

**Comment by vEnhance** [comment]
i actually thought int bee referred to MIT's event by default

**Comment by Incompleteusern** [comment]
Apparently they have renamed the competition to CMM (Caltech Math Meet) or something

**Comment by vEnhance** [comment]
Thanks, let's go with that.

**Pull request merged**
