### PR TITLE
Allow puid as an argument

### PR DESCRIPTION
**Pull request by Incompleteusern**
image

### CODE REVIEW

**Comment by Incompleteusern** [comment]
This is currently broken in `api.py`, pending fix

**Comment by Incompleteusern** [comment]
I've gone and made it so invalid von is supported, this can be exported to a separate pr if desired or removed
image

**Comment by vEnhance** [comment]
```python
        for indice in index:
            index_entry = index[indice]

            if puid == inferPUID(index_entry.source):
                entry = index_entry
                break
```

This looks strange to me. Aren't `indice` and `index_entry.source` the same thing? I thought the index was already a source -> entry map.

**Comment by Incompleteusern** [comment]
oh lol

**Comment by vEnhance** [comment]
Thanks, let's try this out.

**Pull request merged**
